services:
  - type: web
    name: ency-downloader
    runtime: docker
    envVars:
      - key: LEMON_SQUEEZY_CHECKOUT_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
    plan: free
    autoDeploy: true
